name: "Helm package, push & install"
description: "Helm package, push & install"

inputs:
  helm_package_version:
    description: "Helm Package Version"
    required: true
  helm_registry_name:
    description: "Helm Registry Name"
    required: true
  registry_host_name:
    description: "Registry host name"
    required: false
    default: 'us-docker.pkg.dev'
  project_id:
    description: "Google Project Id"
    required: true
  chart_name:
    description: "Chart name"
    required: true

runs:
  using: "composite"
  steps:

      - name: login to artifact registry
        shell: bash
        run: |
          set -x
          gcloud auth configure-docker ${{ inputs.registry_host_name }} --quiet

      - name: helm package
        shell: bash
        run: |
          set -x
          helm dependency build ./charts/${{ inputs.chart_name }}/
          helm package ./charts/${{ inputs.chart_name }}/ --version ${{inputs.helm_package_version}}
      
      - name: helm push
        shell: bash
        run: |
          set -x
          helm push ${{inputs.chart_name}}-${{inputs.helm_package_version}}.tgz oci://${{inputs.registry_host_name}}/${{inputs.project_id}}/${{inputs.helm_registry_name}}
