name: "Docker Build and Push"
description: "Build Docker image and Push to GCR"

inputs:
  appName:
    description: "Name of the application for which tag will be changed"
    required: true
  deployEnv:
    description: "Deploy Env"
    required: true
  tag:
    description: "deploy sha, gittag"
    required: true
  ghaToken:
    description: "Personal github token"
    required: true

runs:
  using: "composite"
  steps:
      - name: Create file for GitHub Auth Token
        shell: bash
        run: |
          echo ${{inputs.ghaToken}}
          curl -v -XPOST -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: token ${{inputs.ghaToken}}'\
          -d ''{"ref": "main", "inputs":{"appName":"${{inputs.appName}}", "deployEnv":"${{inputs.deployEnv}}", "tag":"${{inputs.tag}}''\ 'https://api.github.com/repos/gocariq/environments/actions/workflows/update-tag.yaml/dispatches'