name: "Helm package, push & install"
description: "Helm package, push & install"

inputs:
  google_credentials:
    description: "Google Credentials"
    required: true
  image_tag:
    description: "Google Project Id"
    required: true
  registry_name:
    description: "Docker File Path"
    required: true
  registry_host_name:
    description: "Docker File Path"
    required: true
  project_id:
    description: "Docker Image Name"
    required: true
  gke_google_credentials:
    description: "Docker Repo Name"
    required: true
  cluster_name:
    description: "Google Credentials"
    required: true
  location:
    description: "Google Credentials"
    required: true
  chart_name:
    description: "Google Credentials"
    required: true
  branch_name:
    description: "Branch name for values-$Branch_name.yaml"
    required: true


runs:
  using: "composite"
  steps:

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ inputs.gke_google_credentials }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ inputs.cluster_name }}
          location: ${{ inputs.location }}
          credentials_json: '${{ inputs.gke_google_credentials }}'
      
      - name: helm deploy
        #if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          set -x
          helm -n ${{inputs.branch_name}} upgrade --install ${{inputs.chart_name}} oci://${{inputs.registry_host_name}}/${{inputs.project_id}}/${{inputs.registry_name}}/${{inputs.chart_name}} -f ./charts/${{inputs.chart_name}}/values-${{GITHUB_HEAD_REF}}.yaml --version ${{inputs.image_tag}}
