name: "Docker Build and Push"
description: "Build Docker image and Push to GCR"

inputs:
  google_credentials:
    description: "Google Credentials"
    required: true
  google_project_id:
    description: "Google Project Id"
    required: true
  docker_file_path:
    description: "Docker File Path"
    required: true
  docker_image_name:
    description: "Docker Image Name"
    required: true
  docker_repo_name:
    description: "Docker Repo Name"
    required: true
  docker_params:
    description: "Docker build params"
  docker_build_kit:
    default: "1"
    description: "Build kit some images are not building with 1"

runs:
  using: "composite"
  steps:
      - name: gcp auth
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{inputs.google_project_id}}
          service_account_key: ${{inputs.google_credentials}}
      - name: Docker Auth with gCloud CLI
        shell: bash
        run: |
          gcloud auth configure-docker us-docker.pkg.dev
      - name: Building docker containers
        shell: bash
        run: |
          set -x
          # GITHUB_HEAD_REF is set only for PRs
          if [[ -n $GITHUB_HEAD_REF ]]; then
            GITHUB_SHA=${{github.event.pull_request.head.sha}}
          fi
          echo "GITHUB_SHA=$GITHUB_SHA"
          export SHORT_SHA=${GITHUB_SHA:0:7}
          export REPO_URL="us-docker.pkg.dev"
          export REPO_NAME=${{inputs.docker_repo_name}}
          export IMAGE_NAME=${{inputs.docker_image_name}}
          export IMAGE_TAG=$SHORT_SHA
          export PROJECT_ID=${{inputs.google_project_id}}

          export IMAGE1="$IMAGE_NAME:$IMAGE_TAG"
          export IMAGE2="$IMAGE_NAME:latest"
          export IMAGE_FULL_PATH1="$REPO_URL/$PROJECT_ID/$REPO_NAME/${IMAGE1}"
          export IMAGE_FULL_PATH2="$REPO_URL/$PROJECT_ID/$REPO_NAME/${IMAGE2}"

          # Check image exist in the registry
          set +x
          docker manifest inspect ${IMAGE_FULL_PATH1} > /dev/null
          IMAGE_EXISTS=$?
          set -x
          if [[ "${IMAGE_EXISTS}" == "0" ]]; then
            echo "Image already exists."
            echo "DOCKER PUSH IS SKIPPED"
            exit 1
          fi

          echo "Building docker image $IMAGE1 and $IMAGE2"
          docker images
          
          cd ${{inputs.docker_file_path}}
          DOCKER_BUILDKIT=${{inputs.docker_build_kit}} docker build ${{inputs.docker_params}} -t "$IMAGE1" -t "$IMAGE2" .
          cd -
          docker images

          # Push image if it does not exist in the registry
          echo "Push docker image"
          docker tag $IMAGE1 $IMAGE_FULL_PATH1
          docker tag $IMAGE2 $IMAGE_FULL_PATH2
          docker push $IMAGE_FULL_PATH1
          docker push $IMAGE_FULL_PATH2
