name: "Deploy to Kubernetes"
description: "Authenticate and Deploy to Google Kubernetes Engine"

inputs:
  google_credentials:
    description: "Google Credentials"
    required: true
  google_project_id:
    description: "Google Project Id"
    required: true
  k8s_code_path:
    description: "Path to K8s scripts to deploy"
    required: true
  k8s_cluster_name:
    description: "K8s cluster name"
    required: true
  k8s_cluster_region:
    description: "K8s cluster region"
    required: true

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2
      - name: gcp auth
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{inputs.google_project_id}}
          service_account_key: ${{inputs.google_credentials}}
      - name: Configure for K8s cluster
        shell: bash
        run: |
            set -x
            gcloud config set project ${{inputs.google_project_id}}
            gcloud auth list 
            gcloud config set compute/region ${{inputs.k8s_cluster_region}}
            gcloud container clusters get-credentials ${{inputs.k8s_cluster_name}}
      - name: perform k8s deployment
        shell: bash
        run: |
          kubectl apply -f ${{inputs.k8s_code_path}}
