name: "Helm package, push & install"
description: "Helm package, push & install"

inputs:
  google_credentials:
    description: "Google Credentials"
    required: true
  image_tag:
    description: "Helm Image Tag"
    required: true
  registry_name:
    description: "Docker File Path"
    required: true
  registry_host_name:
    description: "Registry host name"
    required: false
    default: 'us-docker.pkg.dev'
  project_id:
    description: "Google Project Id"
    required: true
  gke_google_credentials:
    description: "Google Kubernetes Engine Credentials"
    required: true
  chart_name:
    description: "Chart name"
    required: true

runs:
  using: "composite"
  steps:
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ inputs.google_credentials }}'

      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: latest

      - name: login to artifact registry
        shell: bash
        run: |
          set -x
          gcloud auth configure-docker ${{ inputs.registry_host_name }} --quiet

      - name: helm package
        shell: bash
        run: |
          set -x
          helm dependency build ./charts/${{ inputs.chart_name }}/
          helm package ./charts/${{ inputs.chart_name }}/ --version ${{inputs.image_tag}}
      
      - name: helm push
        shell: bash
        run: |
          set -x
          helm push ${{inputs.chart_name}}-${{inputs.image_tag}}.tgz oci://${{inputs.registry_host_name}}/${{inputs.project_id}}/${{inputs.registry_name}}
