name: Prepare Release Image
permissions: write-all

on:
  workflow_call:
    inputs:
      project_id:
        default: 'gocariq-platform'
        type: string
      app_name:
        required: true
        type: string
      registry_name:
        default: 'cariq'
        type: string

    secrets:
      GCP_SA_GHA_IMAGEPUSH:
        required: true
      GHA_DEVOPS_DISPATCH:
        required: true
jobs:
  check-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Print Git source branch name
        shell: bash
        run: |
          echo "Target branch - ${{ github.base_ref }}"
          echo "Source branch - ${{ github.head_ref }}"
          echo "Event name    - ${{ github.event_name }}"

      - name: Pull request Validation
        id: PR_Validation
        if: ${{ github.head_ref != 'dev' && github.base_ref == 'main' && github.event_name == 'pull_request' }}
        shell: bash
        run: |
            echo "Pull request to the Main branch was not created from the dev branch. Failing the pipeline..."
            exit 1

      - name: Workflow dispatch Validation
        id: WD_Validation
        if: ${{ github.ref != 'refs/heads/main' && github.event_name == 'workflow_dispatch' }}
        shell: bash
        run: |
            echo "You can RUN the pipeline only from the main branch. Failing the pipeline..."
            exit 1

      - name: Check out repository
        id: CheckOut
        uses: actions/checkout@master
        with:
          fetch-depth: 2

      # - name: Check status of second workflow run
      #   env:
      #     PAT_TOKEN: ${{ secrets.GHA_DEVOPS_DISPATCH }}
      #   run: |
      #     response=$(curl -s -H "Authorization: Bearer $PAT_TOKEN" \
      #       "https://api.github.com/repos/gocariq/${{ inputs.app_name }}/actions/runs")
      #     echo "$response"
      #     status=$(echo "$response" | jq -r '.status')
      #     echo "Status of workflow run: $status"

      - name: Check workflow runs
        id: workflow_runs
        shell: bash
        run: |
          gh run list -L 5 --json --jq='.status' #--workflow BuildAndDeploy.yaml # in_progress

          gh run watch && notify-send "run is done!"
        env:
          GITHUB_TOKEN: ${{secrets.GHA_DEVOPS_DISPATCH}}

      # - run: |
      #     gh api -X GET /repos/${{ GITHUB.REPOSITORY }}/topics --jq='.names'
      #   env:
      #     GH_TOKEN: ${{secrets.GHA_DEVOPS_DISPATCH}}


      - name: Get Git source branch sha
        id: git_source_branch_sha
        shell: bash
        run: |
          set -x
          GIT_SOURCE_BRANCH_SHA=$(git log -n 1 |grep "Merge:\s*\d*\s*\d*" | awk "{print \$3}")
          echo "GIT_SOURCE_BRANCH_SHA=${GIT_SOURCE_BRANCH_SHA}" >> $GITHUB_ENV

      - name: Checking the availability of the image
        id: ImageCheck
        uses: gocariq-gitops/release-actions/actionCheckDockerImage@v2
        with:
          google_credentials: ${{secrets.GCP_SA_GHA_IMAGEPUSH}}
          google_project_id: ${{ inputs.project_id }}
          docker_repo_name:  ${{ inputs.registry_name }}
          docker_image_name: ${{ inputs.app_name }}
          docker_image_tag: ${{ env.GIT_SOURCE_BRANCH_SHA }}

      - name: Stop if the image doesn't exist
        id: CheckImage
        if: ${{ env.IMAGE_EXIST == 'false' }}
        shell: bash
        run: |
            echo "The image does not exist in Dev Repo. Stopping Pipeline."
            exit 1

      - name: Export ENV variables
        id: export_env_vars
        shell: bash
        run: |
          set -x
          
          echo "IMAGE_PATH=${{ env.IMAGE_PATH }}" >> $GITHUB_OUTPUT
          echo "CURRENT_IMAGE=${{ env.CURRENT_IMAGE }}" >> $GITHUB_OUTPUT
          echo "GIT_SOURCE_BRANCH_SHA=${{ env.GIT_SOURCE_BRANCH_SHA }}" >> $GITHUB_OUTPUT

    outputs:
      GIT_SOURCE_BRANCH_SHA: "${{ steps.export_env_vars.outputs.GIT_SOURCE_BRANCH_SHA }}"
      IMAGE_PATH: "${{ steps.export_env_vars.outputs.IMAGE_PATH }}"
      CURRENT_IMAGE: "${{ steps.export_env_vars.outputs.CURRENT_IMAGE }}"

  # run on pull_request to main only
  check-int-deployment:
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
    needs:
      - check-image
    runs-on: ubuntu-22.04
    steps:
      - name: Validate INT environment
        id: Validate_INT_Environment
        uses: gocariq-gitops/release-actions/actionServiceIsDeployed@v2
        with:
          token: ${{ secrets.GHA_DEVOPS_DISPATCH }}
          app_name: ${{ inputs.app_name }}
          env_name: int
          expected_git_tag: "${{ needs.check-image.outputs.GIT_SOURCE_BRANCH_SHA }}"
          on_not_deployed_stop: "true"

  # run on pull_request to main only
  check-stage-deployment:
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
    needs:
      - check-image
    runs-on: ubuntu-22.04
    steps:
      - name: Validate STAGE environment
        id: Validate_STAGE_Environment
        uses: gocariq-gitops/release-actions/actionServiceIsDeployed@v2
        with:
          token: ${{ secrets.GHA_DEVOPS_DISPATCH }}
          app_name: ${{ inputs.app_name }}
          env_name: stage
          expected_git_tag: "${{ needs.check-image.outputs.GIT_SOURCE_BRANCH_SHA }}"
          on_not_deployed_stop: "true"

  # run on merge to main only
  prepare-prod-image:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}

    needs:
      - check-image
    steps:
      - name: Check out repository
        id: CheckOut
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: GCP Auth
        id: GCP_Auth
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ inputs.project_id }}
          service_account_key: ${{secrets.GCP_SA_GHA_IMAGEPUSH}}

      - name: Docker Auth
        id: Docker_Auth
        shell: bash
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Get Next Version
        id: Get_PROD_version
        shell: bash
        run: |
          NEXT_VERSION=$(docker run --rm -v $(pwd):/app -w /app --entrypoint "" us-docker.pkg.dev/gocariq-platform/cariq/semver-helper \
              sh -c "git config --global --add safe.directory /app && semver-helper --next-ver")
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
          if [[ -z $(git tag -l |grep "${NEXT_VERSION}") ]]; then
            git tag ${NEXT_VERSION}
            git push --tags
          else
            echo ""
            echo "It seems you have re-run this job, git tag '${NEXT_VERSION}' already exists."
            echo "NOTE: This run doesn't bring any changes."
          fi
          
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Create PROD version of Image
        id: Create_PROD_version
        shell: bash
        run: |
          set -x

          CURRENT_IMAGE="${{ needs.check-image.outputs.CURRENT_IMAGE }}"
          IMAGE_PATH="${{ needs.check-image.outputs.IMAGE_PATH }}"
          
          echo "Update microservice version '${CURRENT_IMAGE}' -> '${{ env.NEXT_VERSION }}'"
          NEW_IMAGE_PATH="${IMAGE_PATH}:${{ env.NEXT_VERSION }}"
          echo "new image - $NEW_IMAGE_PATH"
          docker pull ${CURRENT_IMAGE}
          docker tag ${CURRENT_IMAGE} $NEW_IMAGE_PATH
          docker push $NEW_IMAGE_PATH
